# This is a TOML document. Boom
perf = "0.0.0.0:8010"

[regions]
    "bj" = ["北京","天津","河北","山东","山西","内蒙古","辽宁","吉林","黑龙江","甘肃","宁夏","新疆"]
    "sh" = ["上海","江苏","浙江","安徽","江西","湖北","重庆","陕西","青海","河南","台湾"]
    "gz" = ["广东","福建","广西","海南","湖南","四川","贵州","云南","西藏","香港","澳门"]
    
[node]
    defaultDomain = "goim.tony.wiki"
    hostDomain = ".goim.tony.wiki"
    heartbeat = "30s"
	heartbeatMax = 3
    tcpPort = 8001
    wsPort = 8002
    wssPort = 8003
    regionWeight = 1.6

[backoff]
    maxDelay = 300
    baseDelay = 3
    factor = 1.8
    jitter = 0.3

[env]
    region = "sh"
	zone = "sh001"
	env = "dev"
	host = "test"
	weight = 10
	ipAddrs = ["127.0.0.1"]

[discovery]
	nodes = ["127.0.0.1:7171"]

[rpcServer]
	dial = "100ms"
	timeout = "500ms"

[rpcClient]
    addr = "0.0.0.0:8019"
    timeout = "1s"

[httpServer]
    addr = "0.0.0.0:8011"
	readTimeout = "1s"
	writeTimeout = "1s"

[kafka]
    topic = "goimPush-topic"
    brokers = ["127.0.0.1:9092"]

[redis]
	network = "tcp"
	addr = "127.0.0.1:6379"
	active = 60000
	idle = 32
	dialTimeout = "50ms"
	readTimeout = "500ms"
	writeTimeout = "500ms"
	idleTimeout = "30s"
	expire = "30m"
