# This is a TOML document. Boom
perf = "0.0.0.0:8010"

[env]
    region = "hk"
	zone = "hk001"
	env = "dev"
	host = "test"

[discovery]
	nodes = ["hk001.tony.wiki:7171"]

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group"
    brokers = ["127.0.0.1:9092"]
