# This is a TOML document. Boom
debug = true
perf = "0.0.0.0:7820"
maxproc = 32
serverTick = "5s"
onlineTick = "10s"

[env]
    region = "hk"
	zone = "hk001"
	env = "dev"
	host = "test"
	weight = 10
	ipAddrs = ["hk001.tony.wiki"]

[discovery]
	nodes = ["hk001.tony.wiki:7171"]

[rpcServer]
    network = "tcp"
    addr = "0.0.0.0:8009"
    timeout = "1s"

[rpcClient]
    dial = "1s"
    timeout = "1s"

[tcp]
    bind = ["0.0.0.0:8001"]
    sndbuf = 4096
    rcvbuf = 4096
    keepalive = false
    reader = 32
    readBuf = 1024
    readBufSize = 2048
    writer = 32
    writeBuf = 1024
    writeBufSize = 2048

[webSocket]
    bind = ["0.0.0.0:8002"]
    tlsOpen = false
    tlsBind = ["0.0.0.0:8003"]
    certFile = "../../cert.pem"
    privateFile = "../../private.pem"

[timer]
    timer = 32
    timerSize = 2048

[protoSection]
    handshakeTimeout = "8s"
    writeTimeout = "8s"
    svrProto = 10
    cliProto = 5

[whitelist]
    Whitelist = [123]
    WhiteLog  = "/tmp/white_list.log"

[bucket]
    size = 32
    channel = 1024
    room = 1024
    routineAmount = 32
    routineSize = 1024
